version: '3.9'

services:
  wasipay-image-server:
    container_name: wasipay-image-server
    image: ghcr.io/minimalcompact/thumbor:latest    
    ports:
      - "8888:80"
    volumes:
      - ./thumbor.conf:/app/thumbor.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: wasipay
      MONGO_INITDB_ROOT_PASSWORD: wasipay